version: '3'

include:
  - db.docker-compose.yaml

services:
  gateway:
    image: olegdayo/gateway:${TAG}
    ports:
      - '8080:8080'
    depends_on:
      gateway-db:
        condition: service_healthy

  integrator:
    image: olegdayo/integrator:${TAG}
    ports:
      - '8081:8080'

  validator:
    image: olegdayo/validator:${TAG}
    ports:
      - '8082:8080'

  web-app:
    image: olegdayo/web-app:${TAG}
    ports:
      - '3000:3000'
