version: '3'

services:
  gateway:
    image: olegdayo/gateway:${TAG}
    ports:
      - '8080:8080'

  integrator:
    image: olegdayo/integrator:${TAG}
    ports:
      - '8081:8080'

  validator:
    image: olegdayo/validator:${TAG}
    ports:
      - '8082:8080'
