apiVersion: v2
name: gateway
description: A Helm chart for GateWay service

type: application

version: 0.1.0

appVersion: "0.1.0"

dependencies:
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 11.1.3
