---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: sse-project
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: sse-project
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /sse-project
            pathType: Prefix
            backend:
              service:
                name: app-service
                port:
                  number: 80
