apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-pv
  labels:
    type: gateway
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
