version: '3'


services:
  gateway:
    image: olegdayo/gateway:${TAG}
    ports:
      - '8080:8080'
    depends_on:
      gateway-db:
        condition: service_healthy

  integrator:
    image: olegdayo/integrator:${TAG}
    ports:
      - '8081:8080'

  pingus:
    image: olegdayo/pingus:${TAG}
    ports:
      - '8082:8080'

  validator:
    image: olegdayo/validator:${TAG}
    ports:
      - '8083:8080'

  web-app:
    image: olegdayo/web-app:${TAG}
    ports:
      - '3000:3000'

  gateway-db:
    image: postgres:15.1
    hostname: gateway-db
    environment:
      POSTGRES_DB: specifications
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - gateway-data:/var/lib/postgresql/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d specifications" ]
      interval: 5s
      timeout: 5s
      retries: 100
      start_period: 10s

volumes:
  gateway-data:
